-- Add n8n_wait_url column to request_steps for storing the dynamic resume URL
-- This URL is generated by n8n's Wait node and must be POSTed to resume the workflow

ALTER TABLE request_steps 
ADD COLUMN IF NOT EXISTS n8n_wait_url TEXT;

-- Add index for efficient lookup when resuming workflows
CREATE INDEX IF NOT EXISTS idx_request_steps_n8n_wait_url ON request_steps(n8n_wait_url) WHERE n8n_wait_url IS NOT NULL;

COMMENT ON COLUMN request_steps.n8n_wait_url IS 'Dynamic webhook URL from n8n Wait node - POST to this URL to resume the workflow';
